extends Node

# --- ROAD ENUMS ---
enum RoadType { UNKNOWN, STRAIGHT, CORNER, T_JUNCTION, INTERSECTION, END }
enum MajorRoadType { UNKNOWN, STRAIGHT, T_JUNCTION, INTERSECTION_CORNER, INTERSECTION_FILLER }
enum MajorRoadLaneType { EDGE, MIDDLE, ODD_CENTER, EVEN_CENTER }

# --- PLAYER ENUMS ---
enum PlayerClass { UNASSIGNED, HERO, VILLAIN, SUPPORT_GOOD, SUPPORT_EVIL, SUPPORT_ANTI, THREAT}
