extends Node

enum RoadType { UNKNOWN, STRAIGHT, CORNER, T_JUNCTION, CROSSROADS, END }
enum MajorRoadType { UNKNOWN, STRAIGHT, T_JUNCTION, INTERSECTION_PIECE }
enum MajorRoadLaneType { EDGE, MIDDLE, ODD_CENTER, EVEN_CENTER }
