extends Node

enum RoadType { UNKNOWN, STRAIGHT, CORNER, T_JUNCTION, INTERSECTION, END }
enum MajorRoadType { UNKNOWN, STRAIGHT, T_JUNCTION, INTERSECTION_CORNER, INTERSECTION_FILLER }
enum MajorRoadLaneType { EDGE, MIDDLE, ODD_CENTER, EVEN_CENTER }
